#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="p3ng0s"
iso_label="ARCH_$(date +%Y%m)"
iso_publisher="p4p1 <https://leosmith.wtf>"
iso_application="p3ng0s Live/Rescue CD"
iso_version="$(date +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
           'uefi-ia32.grub.esp' 'uefi-x64.grub.esp'
           'uefi-ia32.grub.eltorito' 'uefi-x64.grub.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.dwm/bar.sh"]="0:0:755"
  ["/root/.dwm/wallpaper.sh"]="0:0:755"
  ["/root/.fzf/bin/fzf-tmux"]="0:0:755"
  ["/root/.fzf/bin/fzf"]="0:0:755"
  ["/opt/dwmstat/bin/dwmstat"]="0:0:755"
  ["/opt/dwmstat/bin/sound.sh"]="0:0:755"
  ["/opt/dwmstat/bin/brightness.sh"]="0:0:755"
  ["/opt/Responder/tools/Icmp-Redirect.py"]="0:0:755"
  ["/opt/Responder/tools/SMBFinger/Finger.py"]="0:0:755"
  ["/opt/Responder/tools/MultiRelay.py"]="0:0:755"
  ["/opt/Responder/tools/BrowserListener.py"]="0:0:755"
  ["/opt/Responder/tools/FindSQLSrv.py"]="0:0:755"
  ["/opt/Responder/tools/RunFinger.py"]="0:0:755"
  ["/opt/Responder/tools/MultiRelay/impacket-dev/impacket/dcerpc/v5/dhcpm.py"]="0:0:755"
  ["/opt/Responder/tools/MultiRelay/impacket-dev/secretsdump.py"]="0:0:755"
  ["/opt/Responder/DumpHash.py"]="0:0:755"
  ["/opt/Responder/utils.py"]="0:0:755"
  ["/opt/Responder/Report.py"]="0:0:755"
  ["/opt/Responder/Responder.py"]="0:0:755"
  ["/opt/Responder/certs/gen-self-signed-cert.sh"]="0:0:755"
  ["/opt/Responder/settings.py"]="0:0:755"
  ["/opt/Responder/servers/RDP.py"]="0:0:755"
  ["/opt/Responder/servers/HTTP.py"]="0:0:755"
  ["/opt/Responder/servers/HTTP_Proxy.py"]="0:0:755"
  ["/opt/Responder/servers/MSSQL.py"]="0:0:755"
  ["/opt/Responder/servers/FTP.py"]="0:0:755"
  ["/opt/Responder/servers/DNS.py"]="0:0:755"
  ["/opt/Responder/poisoners/LLMNR.py"]="0:0:755"
  ["/opt/Responder/poisoners/DHCP.py"]="0:0:755"
  ["/opt/Responder/poisoners/NBTNS.py"]="0:0:755"
  ["/opt/Responder/poisoners/MDNS.py"]="0:0:755"
  ["/opt/Responder/packets.py"]="0:0:755"
  ["/opt/larp/install.sh"]="0:0:755"
  ["/opt/larp/bin/larp"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
)
