# ==========================
# ===  General Settings  ===
# ==========================
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g history-limit 50000
set -g allow-rename off
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1

set-window-option -g mode-keys vi
set-option -g default-shell /bin/bash

# Crucial for hex color rendering
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# ==========================
# ===    Key Bindings    ===
# ==========================
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind S set-window-option synchronize-panes \; display "Sync mode toggled!"
bind P pipe-pane -o "cat >> /tmp/tmux-#W-$(date +%Y%m%d-%H%M%S).log" \; display "Toggled logging to /tmp/tmux-#W-$(date +%Y%m%d-%H%M%S).log"

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Reload shortcut
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# ==========================
# ===   Design/Styling   ===
# ==========================

set-option -g status-position top
# Alignment: This moves the window list to the left
set -g status-justify left

# Main Status Bar: Orange Background, Dark Text
set -g status-style bg="#393939",fg="#ff875f"

# Left Side: Session Name (Inverted for pop)
set -g status-left "#[bg=#ff875f,fg=#393939] #S #[default] "

# Right Side: Date and Time (Dark text on Orange)
set -g status-right-length 300
set -g status-right "#(tmux show-env IP 2>/dev/null | grep -q '^IP=' && echo '#[bg=#ff875f,fg=#393939] [ IP='$(tmux show-env IP | cut -d= -f2)' ]')#(tmux show-env DNS 2>/dev/null | grep -q '^DNS=' && echo '#[bg=#ff875f,fg=#393939] [ DNS='$(tmux show-env DNS | cut -d= -f2)' ]')#(tmux show-env USERNAME 2>/dev/null | grep -q '^USERNAME=' && echo '#[bg=#ff875f,fg=#393939] [ USER='$(tmux show-env USERNAME | cut -d= -f2)' ]')#(tmux show-env PASSWORD 2>/dev/null | grep -q '^PASSWORD=' && echo '#[bg=#ff875f,fg=#393939] [ PASSWORD='$(tmux show-env PASSWORD | cut -d= -f2)' ]')#(tmux show-env HASH 2>/dev/null | grep -q '^HASH=' && echo '#[bg=#ff875f,fg=#393939] [ HASH='$(tmux show-env HASH | cut -d= -f2)' ]')#(tmux show-env KRB5CCNAME 2>/dev/null | grep -q '^KRB5CCNAME=' && echo '#[bg=#ff875f,fg=#393939] [ TKT='$(tmux show-env KRB5CCNAME | cut -d= -f2)' ]')#(tmux show-env SCOPE 2>/dev/null | grep -q '^SCOPE=' && echo '#[bg=#ff875f,fg=#393939] [ SCOPE='$(tmux show-env SCOPE | cut -d= -f2)' ]')#(tmux show-env URL 2>/dev/null | grep -q '^URL=' && echo '#[bg=#ff875f,fg=#393939] [ URL='$(tmux show-env URL | cut -d= -f2)' ]')#[bg=#ff875f,fg=#393939] [ #{user}@#h ] "


#set -g status-right "#[bg=#ff875f,fg=#393939] [ #{user}@#h ] "

# Window List: 
# Active Window: Dark background with Orange text
set-window-option -g window-status-current-style bg="#ff875f",fg="#393939",bold
set-window-option -g window-status-current-format " #I:#W "

# Inactive Windows: Dark text on the Orange bar
set-window-option -g window-status-style fg="#ff875f",bg="#393939"
set-window-option -g window-status-format " #I:#W "

# Pane Borders (Orange for active, dark for inactive)
set -g pane-border-style fg="#393939"
set -g pane-active-border-style fg="#ff875f"

# Message/Command Prompt
set -g message-style bg="#393939",fg="#ff875f",bold
